ALTER TABLE USERS
	ADD COLUMN CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN CREATOR_ID VARCHAR(100) NOT NULL DEFAULT 'NOBODY',
	ADD COLUMN LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN LAST_UPD_ID VARCHAR(100) DEFAULT NULL;

ALTER TABLE AUTHORITIES
	ADD COLUMN CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN CREATOR_ID VARCHAR(100) NOT NULL DEFAULT 'NOBODY',
	ADD COLUMN LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN LAST_UPD_ID VARCHAR(100) DEFAULT NULL;

ALTER TABLE USER_AUTHORITIES
	ADD COLUMN CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN CREATOR_ID VARCHAR(100) NOT NULL DEFAULT 'NOBODY',
	ADD COLUMN LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN LAST_UPD_ID VARCHAR(100) DEFAULT NULL;

ALTER TABLE GROUP_AUTHORITIES
	ADD COLUMN CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN CREATOR_ID VARCHAR(100) NOT NULL DEFAULT 'NOBODY',
	ADD COLUMN LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN LAST_UPD_ID VARCHAR(100) DEFAULT NULL;

ALTER TABLE GROUPS
	ADD COLUMN CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN CREATOR_ID VARCHAR(100) NOT NULL DEFAULT 'NOBODY',
	ADD COLUMN LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN LAST_UPD_ID VARCHAR(100) DEFAULT NULL;

ALTER TABLE GROUP_MEMBERS
	ADD COLUMN CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN CREATOR_ID VARCHAR(100) NOT NULL DEFAULT 'NOBODY',
	ADD COLUMN LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN LAST_UPD_ID VARCHAR(100) DEFAULT NULL;
	
CREATE TABLE DB_VERSION(
	DB_VERSION INT(11),
	CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATOR_ID VARCHAR(100) NOT NULL DEFAULT 'NOBODY',
	LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LAST_UPD_ID VARCHAR(100) DEFAULT NULL
);

INSERT INTO DB_VERSION (DB_VERSION, CREATED_DATE, CREATOR_ID, LAST_UPD_DATE, LAST_UPD_ID) VALUES (0,NOW(), 'Suyash', NOW(), 'Suyash');

CREATE TABLE REF_CODES (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  REF_CODE_GROUP_ID INT(11) NOT NULL,
  CODE VARCHAR(150) NOT NULL,
  VALUE VARCHAR(150) NOT NULL,
  ACTIVE TINYINT(1) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATOR_ID VARCHAR(100) NOT NULL,
  LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_UPD_ID VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=INNODB AUTO_INCREMENT=1;

CREATE TABLE REF_CODE_GROUPS (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  CODE VARCHAR(50) NOT NULL,
  LABEL VARCHAR(50) NOT NULL,
  ACTIVE TINYINT(1) NOT NULL,
  UI_MANAGEABLE TINYINT(1) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATOR_ID VARCHAR(100) NOT NULL,
  LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_UPD_ID VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY (CODE)
) ENGINE=INNODB AUTO_INCREMENT=1;

UPDATE DB_VERSION SET DB_VERSION = 1, LAST_UPD_DATE=CURRENT_TIMESTAMP, LAST_UPD_ID = 'Suyash';