ALTER TABLE USERS
	ADD COLUMN CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN CREATOR_ID VARCHAR(100) NOT NULL DEFAULT 'NOBODY',
	ADD COLUMN LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN LAST_UPD_ID VARCHAR(100) DEFAULT NULL;

ALTER TABLE AUTHORITIES
	ADD COLUMN CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN CREATOR_ID VARCHAR(100) NOT NULL DEFAULT 'NOBODY',
	ADD COLUMN LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN LAST_UPD_ID VARCHAR(100) DEFAULT NULL;

ALTER TABLE USER_AUTHORITIES
	ADD COLUMN CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN CREATOR_ID VARCHAR(100) NOT NULL DEFAULT 'NOBODY',
	ADD COLUMN LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN LAST_UPD_ID VARCHAR(100) DEFAULT NULL;

ALTER TABLE GROUP_AUTHORITIES
	ADD COLUMN CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN CREATOR_ID VARCHAR(100) NOT NULL DEFAULT 'NOBODY',
	ADD COLUMN LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN LAST_UPD_ID VARCHAR(100) DEFAULT NULL;

ALTER TABLE GROUPS
	ADD COLUMN CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN CREATOR_ID VARCHAR(100) NOT NULL DEFAULT 'NOBODY',
	ADD COLUMN LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN LAST_UPD_ID VARCHAR(100) DEFAULT NULL;

ALTER TABLE GROUP_MEMBERS
	ADD COLUMN CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN CREATOR_ID VARCHAR(100) NOT NULL DEFAULT 'NOBODY',
	ADD COLUMN LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN LAST_UPD_ID VARCHAR(100) DEFAULT NULL;
	
CREATE TABLE DB_VERSION(
	DB_VERSION INT(11),
	CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATOR_ID VARCHAR(100) NOT NULL DEFAULT 'NOBODY',
	LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LAST_UPD_ID VARCHAR(100) DEFAULT NULL
);

INSERT INTO DB_VERSION (DB_VERSION, CREATED_DATE, CREATOR_ID, LAST_UPD_DATE, LAST_UPD_ID) VALUES (0,NOW(), 'Suyash', NOW(), 'Suyash');

CREATE TABLE REF_CODES (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  REF_CODE_GROUP_ID INT(11) NOT NULL,
  CODE VARCHAR(150) NOT NULL,
  VALUE VARCHAR(150) NOT NULL,
  ACTIVE TINYINT(1) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATOR_ID VARCHAR(100) NOT NULL,
  LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_UPD_ID VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=INNODB AUTO_INCREMENT=1;

CREATE TABLE REF_CODE_GROUPS (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  CODE VARCHAR(50) NOT NULL,
  LABEL VARCHAR(50) NOT NULL,
  ACTIVE TINYINT(1) NOT NULL,
  UI_MANAGEABLE TINYINT(1) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATOR_ID VARCHAR(100) NOT NULL,
  LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_UPD_ID VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY (CODE)
) ENGINE=INNODB AUTO_INCREMENT=1;

UPDATE DB_VERSION SET DB_VERSION = 1, LAST_UPD_DATE=CURRENT_TIMESTAMP, LAST_UPD_ID = 'Suyash';

ALTER TABLE USERS 
	ADD COLUMN USER_PROFILE_ID INT(11) NOT NULL,
	ADD COLUMN EMAIL VARCHAR(200) NOT NULL,
	ADD COLUMN FIRST_NAME VARCHAR(200) NOT NULL,
	ADD COLUMN LAST_NAME VARCHAR(200) NOT NULL;
	
CREATE TABLE STATES (
  STATE_ID INT(11) NOT NULL AUTO_INCREMENT,
  COUNTRY_ID INT(11) NOT NULL,
  STATE_CODE VARCHAR(10) NOT NULL,
  STATE_NAME VARCHAR(100) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATOR_ID VARCHAR(100) NOT NULL,
  LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_UPD_ID VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (STATE_ID)
) ENGINE=INNODB AUTO_INCREMENT=1;	

CREATE TABLE COUNTRIES (
  COUNTRY_ID INT(11) NOT NULL AUTO_INCREMENT,
  COUNTRY_CODE VARCHAR(10) NOT NULL,
  COUNTRY_NAME VARCHAR(100) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATOR_ID VARCHAR(100) NOT NULL,
  LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_UPD_ID VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (COUNTRY_ID)
) ENGINE=INNODB AUTO_INCREMENT=1;


CREATE TABLE ADDRESSES (
  ADDR_ID INT(11) NOT NULL AUTO_INCREMENT,
  CITY VARCHAR(100) NULL,
  STATE_ID INT(11) NOT NULL,
  COUNTRY_ID INT(11) NOT NULL,
  ZIP VARCHAR(100) NULL,
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATOR_ID VARCHAR(100) NOT NULL,
  LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_UPD_ID VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (ADDR_ID)
) ENGINE=INNODB AUTO_INCREMENT=1;	

CREATE TABLE USER_PROFILE (
  USER_PROFILE_ID INT(11) NOT NULL AUTO_INCREMENT,
  GENDER VARCHAR(10) NULL,
  DATE_OF_BIRTH DATE NULL,
  RELIGION INT(11) NULL,
  ADDR_ID INT(11) NULL,
  MOTHER_TONGUE INT(11) NULL,
  MOBILE_NUMBER VARCHAR(50) NULL,
  MARITAL_STATUS INT(11) NULL,
  EDUCATIONAL_LEVEL INT(11) NULL,
  EDUCATIONAL_FIELD VARCHAR(100) NULL,
  WORKING_WITH INT(11) NULL,
  WORKING_AS VARCHAR(200),
  ANNUAL_INCOME INT(11) NULL,
  SELF_DESCRIPTION TEXT,
  DISABILITY TINYINT(1),
  HEIGHT INT(11) NULL,
  DIET INT(11) NULL,
  DRINK TINYINT(1),
  SMOKE TINYINT(1),
  HIV_POSITIVE TINYINT(1),
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATOR_ID VARCHAR(100) NOT NULL,
  LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_UPD_ID VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (USER_PROFILE_ID)
) ENGINE=INNODB AUTO_INCREMENT=1;

INSERT INTO REF_CODE_GROUPS
(CODE, LABEL, ACTIVE, UI_MANAGEABLE, CREATED_DATE, CREATOR_ID, LAST_UPD_DATE, LAST_UPD_ID) 
VALUES 
( 'PROFILE_RELIGION', 'Profile religion', 1, 1, NOW(), 'archadmin', NOW(), 'archadmin'),
( 'PROFILE_MOTHER_TONGUE', 'Profile mother tongue', 1, 1, NOW(), 'archadmin', NOW(), 'archadmin'),
( 'PROFILE_MARITAL_STATUS', 'Profile marital status', 1, 1, NOW(), 'archadmin', NOW(), 'archadmin'),
( 'PROFILE_EDUCATIONAL_LEVEL', 'Profile educational level', 1, 1, NOW(), 'archadmin', NOW(), 'archadmin'),
( 'PROFILE_WORK_WITH', 'Profile Work With', 1, 1, NOW(), 'archadmin', NOW(), 'archadmin'),
( 'PROFILE_ANNUAL_INCOME', 'Profile annual income', 1, 1, NOW(), 'archadmin', NOW(), 'archadmin');	

-- RELIGION
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'HINDU', 'Hindu', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_RELIGION';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'MUSLIM', 'Muslim', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_RELIGION';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'CHISTIAN', 'Chistian', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_RELIGION';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'SIKH', 'Sikh', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_RELIGION';

-- MOTHER_TONGUE
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'ENGLISH', 'English', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_MOTHER_TONGUE';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'HINDI', 'Hindi', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_MOTHER_TONGUE';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'TELUGU', 'Telugu', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_MOTHER_TONGUE';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'BENGALI', 'Bengali', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_MOTHER_TONGUE';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'GUJRATI', 'Gujrati', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_MOTHER_TONGUE';

-- MARITAL_STATUS
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'SINGLE', 'Single', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_MARITAL_STATUS';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'MARRIED', 'Married', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_MARITAL_STATUS';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'SEPARATED', 'Separated', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_MARITAL_STATUS';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'WIDOW', 'widow', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_MARITAL_STATUS';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'DIVORCEE', 'Divorcee', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_MARITAL_STATUS';

-- EDUCATIONAL_LEVEL
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'ILLITERATE', 'Illiterate', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_EDUCATIONAL_LEVEL';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'HIGH_SCHOOL', 'High School', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_EDUCATIONAL_LEVEL';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'INTERMEDIATE', 'Intermediate', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_EDUCATIONAL_LEVEL';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'BACHELORS', 'Bachelors', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_EDUCATIONAL_LEVEL';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'MASTERS', 'Masters', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_EDUCATIONAL_LEVEL';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'PHD', 'Ph.D', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_EDUCATIONAL_LEVEL';

-- WORK_WITH
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'PRIVATE', 'Private', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_WORK_WITH';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'PUBLIC', 'Public', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_WORK_WITH';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'DEFENCE', 'Defence', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_WORK_WITH';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'OWN_BUSINESS', 'Own Business', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_WORK_WITH';

-- JOB SALARIES
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '100K+', '100,000 and above', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_ANNUAL_INCOME';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '80K-100K', '80,000 - 100,000', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_ANNUAL_INCOME';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '60K-80K', '60,000 - 80,000', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_ANNUAL_INCOME';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '40K-60K', '40,000 - 60,000', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_ANNUAL_INCOME';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '20K-40K', '20,000 - 40,000', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_ANNUAL_INCOME';
INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '20K+', '20,000 and below', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_ANNUAL_INCOME';

UPDATE DB_VERSION SET DB_VERSION = 2, LAST_UPD_DATE=CURRENT_TIMESTAMP, LAST_UPD_ID = 'Ramya';


INSERT INTO countries (COUNTRY_CODE, COUNTRY_NAME) VALUES
('IN', 'India'),
('US', 'United States');

INSERT INTO states (COUNTRY_ID, STATE_NAME, STATE_CODE) VALUES ( '1','ANDHRA PRADESH','AP'),
 ( '1','ASSAM','AS'),
 ( '1','ARUNACHAL PRADESH','AR'),
 ( '1','GUJRAT','GJ'),
 ( '1','BIHAR','BR'),
 ( '1','HARYANA','HR'),
 ( '1','HIMACHAL PRADESH','HP'),
 ( '1','JAMMU & KASHMIR','JK'),
 ( '1','KARNATAKA','KA'),
 ( '1','KERALA','KL'),
 ( '1','MADHYA PRADESH','MP'),
 ( '1','MAHARASHTRA','MH'),
 ( '1','MANIPUR','MN'),
 ( '1','MEGHALAYA','ML'),
 ( '1','MIZORAM','MZ'),
 ( '1','NAGALAND','NL'),
 ( '1','ORISSA','OR'),
 ( '1','PUNJAB','PB'),
 ( '1','RAJASTHAN','RJ'),
 ( '1','SIKKIM','SK'),
 ( '1','TAMIL NADU','TN'),
 ( '1','TRIPURA','TR'),
 ( '1','UTTAR PRADESH','UP'),
 ( '1','WEST BENGAL','WB'),
 ( '1','DELHI','DL'),
 ( '1','GOA','GA'),
 ( '1','PONDICHERY','PY'),
 ( '1','LAKSHDWEEP','LD'),
 ( '1','DAMAN & DIU','DD'),
 ( '1','DADRA & NAGAR','DH'),
 ( '1','CHANDIGARH','CH'),
 ( '1','ANDAMAN & NICOBAR','AN'),
 ( '1','UTTARANCHAL','UK'),
 ( '1','JHARKHAND','JH'),
 ( '1','CHATTISGARH','CG'),
 ( '1','TELANGANA ','TS');

INSERT INTO states (COUNTRY_ID, STATE_NAME, STATE_CODE)
VALUES
( 2, 'Alabama', 'AL'),
( 2, 'Alaska', 'AK'),
( 2, 'Arizona', 'AZ'),
( 2, 'Arkansas', 'AR'),
( 2, 'California', 'CA'),
( 2, 'Colorado', 'CO'),
( 2, 'Connecticut', 'CT'),
( 2, 'Delaware', 'DE'),
( 2, 'District of Columbia', 'DC'),
( 2, 'Florida', 'FL'),
( 2, 'Georgia', 'GA'),
( 2, 'Hawaii', 'HI'),
( 2, 'Idaho', 'ID'),
( 2, 'Illinois', 'IL'),
( 2, 'Indiana', 'IN'),
( 2, 'Iowa', 'IA'),
( 2, 'Kansas', 'KS'),
( 2, 'Kentucky', 'KY'),
( 2, 'Louisiana', 'LA'),
( 2, 'Maine', 'ME'),
( 2, 'Maryland', 'MD'),
( 2, 'Massachusetts', 'MA'),
( 2, 'Michigan', 'MI'),
( 2, 'Minnesota', 'MN'),
( 2, 'Mississippi', 'MS'),
( 2, 'Missouri', 'MO'),
( 2, 'Montana', 'MT'),
( 2, 'Nebraska', 'NE'),
( 2, 'Nevada', 'NV'),
( 2, 'New Hampshire', 'NH'),
( 2, 'New Jersey', 'NJ'),
( 2, 'New Mexico', 'NM'),
( 2, 'New York', 'NY'),
( 2, 'North Carolina', 'NC'),
( 2, 'North Dakota', 'ND'),
( 2, 'Ohio', 'OH'),
( 2, 'Oklahoma', 'OK'),
( 2, 'Oregon', 'OR'),
( 2, 'Pennsylvania', 'PA'),
( 2, 'Rhode Island', 'RI'),
( 2, 'South Carolina', 'SC'),
( 2, 'South Dakota', 'SD'),
( 2, 'Tennessee', 'TN'),
( 2, 'Texas', 'TX'),
( 2, 'Utah', 'UT'),
( 2, 'Vermont', 'VT'),
( 2, 'Virginia', 'VA'),
( 2, 'Washington', 'WA'),
( 2, 'West Virginia', 'WV'),
( 2, 'Wisconsin', 'WI'),
( 2, 'Wyoming', 'WY');

UPDATE DB_VERSION SET DB_VERSION = 2, LAST_UPD_DATE=CURRENT_TIMESTAMP, LAST_UPD_ID = 'Ramya';

INSERT INTO REF_CODE_GROUPS (CODE, LABEL, ACTIVE, UI_MANAGEABLE, CREATED_DATE, CREATOR_ID, LAST_UPD_DATE, LAST_UPD_ID) VALUES 
( 'PROFILE_DIET', 'Profile diet', 1, 1, NOW(), 'archadmin', NOW(), 'archadmin');

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'VEG', 'Vegetarian', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_DIET';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'NON_VEG', 'Non-Vegetarian', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_DIET';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, 'VEGAN', 'Vegan', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_DIET';

INSERT INTO REF_CODE_GROUPS (CODE, LABEL, ACTIVE, UI_MANAGEABLE, CREATED_DATE, CREATOR_ID, LAST_UPD_DATE, LAST_UPD_ID) VALUES 
( 'PROFILE_HEIGHT', 'Profile height', 1, 1, NOW(), 'archadmin', NOW(), 'archadmin');

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '53_INCHES', '4\'5"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '54_INCHES', '4\'6"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '55_INCHES', '4\'7"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '56_INCHES', '4\'8"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '57_INCHES', '4\'9"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '58_INCHES', '4\'10"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '59_INCHES', '4\'11"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '60_INCHES', '5\'0"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '61_INCHES', '5\'1"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '62_INCHES', '5\'2"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '63_INCHES', '5\'3"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '64_INCHES', '5\'4"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '65_INCHES', '5\'5"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '66_INCHES', '5\'6"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '67_INCHES', '5\'7"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '68_INCHES', '5\'8"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '69_INCHES', '5\'9"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '70_INCHES', '5\'10"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '71_INCHES', '5\'11"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '72_INCHES', '6\'0"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '73_INCHES', '6\'1"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '74_INCHES', '6\'2"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '75_INCHES', '6\'3"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '76_INCHES', '6\'4"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '77_INCHES', '6\'5"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '78_INCHES', '6\'6"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '79_INCHES', '6\'7"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '80_INCHES', '6\'8"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '81_INCHES', '6\'9"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '82_INCHES', '6\'10"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '83_INCHES', '6\'11"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

INSERT INTO REF_CODES(REF_CODE_GROUP_ID, CODE, VALUE, ACTIVE, CREATED_DATE, CREATOR_ID) 
SELECT rg.ID, '84_INCHES', '7\'0"', 1, NOW(), 'archadmin' FROM REF_CODE_GROUPS rg WHERE rg.CODE='PROFILE_HEIGHT';

UPDATE DB_VERSION SET DB_VERSION = 3, LAST_UPD_DATE=CURRENT_TIMESTAMP, LAST_UPD_ID = 'Suyash';
